[IMP] industry_restaurant: add website homepage
odoo/industry pull request #120
Opened 2024-04-30 12:55 UTC by dhrs-odoo

[IMP] industry_restaurant: add website homepage

2024-04-30 15:25 UTC, vava-odoo requested changes
Thanks @dhrs-odoo for this nice work.
Please have a look at the following comment. Please also change the commit title to "[IMP] industry_restaurant: add website homepage".
Cheers

2024-04-30 15:25 UTC, vava-odoo commented on industry_restaurant/static/src/binary/ir_attachment/1375.jpg
1374 and 1375 are the same. Can't we keep only one?

2024-04-30 15:25 UTC, vava-odoo commented on industry_restaurant/static/src/binary/ir_attachment/1379-food.jpg
Same comment for 1378 and 1379

2024-04-30 15:25 UTC, vava-odoo commented on industry_restaurant/demo/website_view.xml
> +                            <span class="s_parallax_bg oe_img_bg o_bg_img_center" style="background-image: url('industry_restaurant/static/src/binary/ir_attachment/1379-food.jpg'); background-positio
Do we need the data-original-* values?

2024-04-30 15:25 UTC, vava-odoo commented on industry_restaurant/demo/website_view.xml
> +                        <section class="s_image_gallery o_slideshow s_image_gallery_show_indicators s_image_gallery_indicators_rounded o_colored_level pb0 pt40" data-vcss="001" data-columns="3" style
The carousel doesn't seem to display correctly

2024-05-01 10:07 UTC, dhrs-odoo commented
Hello @vava-odoo 
I have incorporated your suggestions
KIndly please have a look at it once you are free
Thank You :innocent:

2024-05-02 07:11 UTC, merged