[ADD] billboard: Billboard Industry
odoo/industry pull request #151
Opened 2024-06-25 12:24 UTC by dhrs-odoo

Task-3522783

2024-08-26 18:08 UTC, vava-odoo requested changes
Thanks Dhrumil. A few comments but overall it looks good. Thanks!

2024-08-26 18:08 UTC, vava-odoo commented on billboard_rental/demo/crm_stage.xml
> +    </record>
To me it could be moved to data

2024-08-28 06:30 UTC, dhrs-odoo commented on billboard_rental/data/ir_model.xml
> +    </record>
yes

2024-08-28 06:57 UTC, dhrs-odoo commented on billboard_rental/data/ir_ui_view.xml
> +                    <field name="x_state" string="Available"/>
It was somehow not getting applied so I have mentioned it over here as well

2024-08-28 07:18 UTC, dhrs-odoo commented on billboard_rental/data/ir_ui_menu.xml
> +        <field name="web_icon">fa fa-desktop,#262c34,#FFFFFF</field>
ok

2024-08-28 10:01 UTC, dhrs-odoo commented on billboard_rental/data/sale_order_template_line.xml
> +    </record>
No, this is fine

2024-08-28 10:09 UTC, dhrs-odoo commented
Hello @vava-odoo 
I have incorporated all the suggested changes 
Can you please have a look at it once you are free
Thank You :innocent:

2024-08-29 09:47 UTC, vava-odoo requested changes
Hi @dhrs-odoo 
Thanks for the update. Still some comments before merging.
Cheers

2024-08-29 09:47 UTC, vava-odoo commented on billboard_rental/demo/sale_order.xml
> +        <field name="sale_order_template_id" ref="sale_order_template_1"/>
Duplicated (and runbot was telling you)

2024-08-29 09:47 UTC, vava-odoo commented on billboard_rental/data/sale_order_template_line.xml
> +    </record>
Short-term:  plan_id: monthly
Long-term: plan_id: yearly

2024-08-29 09:47 UTC, vava-odoo commented on billboard_rental/data/uom_uom.xml
> +        <field name="factor">0.03333333333333333</field>
This is not the way. You need to use the reccurring price
![image](https://github.com/user-attachments/assets/59d56dd8-a0af-40a7-b32c-17709a5e9c91)

2024-08-29 14:05 UTC, vava-odoo commented on billboard_rental/data/sale_order_template_line.xml
> +    </record>
Confirmed: plan_id (same as for sale.subscription.pricing) to be added in the sale.order.template

2024-08-30 05:26 UTC, dhrs-odoo commented on billboard_rental/data/sale_order_template_line.xml
> +    </record>
Done added the plan_id in the sale.order.template

2024-09-04 15:38 UTC, merged