[ADD] Bar & Pub Industry
odoo/industry pull request #198
Opened 2024-08-21 04:35 UTC by dhrs-odoo

Task - 4069771

2024-09-03 08:56 UTC, vava-odoo requested changes
Thanks @dhrs-odoo 
Here is a first review.
Could you also remove all the unused files listed in the test logs?
Cheers

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/data/product_pricelist.xml
> +        'percent_price': 50})]"/>
```suggestion
        <field name="item_ids" eval="[(0, 0, {
            'display_applied_on': '2_product_category',
            'applied_on' : '2_product_category',
            'categ_id': ref('product.product_category_1'),
            'compute_price': 'percentage',
            'min_quantity': 2,
            'base_pricelist_id': ref('product_pricelist_1'),
            'percent_price': 50,
        })]"/>
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/data/project_task_type.xml
> +    <record id="project_task_type_1" model="project.task.type">
Why do you have duplicates? 1 = 3 and 2 = 4

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/hr_employee.xml
> +<odoo>
add it to the noupdate test as well
```suggestion
<odoo noupdate="1">
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/planning_recurrency.xml
> +        <field name="last_generated_end_datetime">2025-02-17 07:00:00</field>
The default values are: repeat every 1 week forever. Maybe just adapt to limit the number of repetitions:
```suggestion
        <field name="x_times">30</field>
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/data/product_product.xml
> +        <field name="standard_price">2.5</field>
You removed the pos category "beer" that was useful here.

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/planning_recurrency.xml
> +<odoo>
We don't want to update this one either
```suggestion
<odoo noupdate="1">
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/data/uom_uom.xml
> +    </record>
Missing uom for bin

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/data/product_product.xml
> +        <field name="uom_po_id" ref="uom_uom_27"/>
should be bin (24 bottles)

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/product_supplierinfo.xml
> +        <field name="price">1.5</field>
Adapted to the uom_po_id
```suggestion
        <field name="min_qty">1.0</field>
        <field name="price">36.0</field>
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/product_supplierinfo.xml
> +    </record>
```suggestion
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/planning_slot.xml
> +<odoo>
Same, let's harmonize
```suggestion
<odoo noupdate="1">
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/planning_slot.xml
> +        ).astimezone(pytz.UTC).replace(tzinfo=None)
indentation issues

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/purchase_order_line.xml
> +        <field name="price_unit">1.5</field>
```suggestion
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/purchase_order_line.xml
> +        <field name="price_unit">1.5</field>
```suggestion
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/demo/purchase_order_line.xml
> +        <field name="product_qty">48.0</field>
```suggestion
        <field name="product_qty">2.0</field>
```

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/static/src/binary/hr_employee/2-image_1920
useless

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/static/src/binary/hr_employee/3-image_1920
useless

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/static/src/binary/res_partner/14-image_1920
useless

2024-09-03 08:56 UTC, vava-odoo commented on bar_industry/static/src/binary/res_partner/15-image_1920
useless

2024-09-03 12:16 UTC, vava-odoo reviewed
Small update about uom

2024-09-03 12:16 UTC, vava-odoo commented on bar_industry/demo/stock_warehouse_orderpoint.xml
> +        <field name="product_supplier_id" ref="res_partner_13"/>
please add this one
`        <field name="qty_multiple">24.0</field>`

2024-09-03 12:16 UTC, vava-odoo commented on bar_industry/data/product_product.xml
> +        <field name="uom_id" ref="uom_uom_27"/>
We'll work with Units
```suggestion
```

2024-09-03 12:16 UTC, vava-odoo commented on bar_industry/data/product_product.xml
> +        <field name="uom_po_id" ref="uom_uom_27"/>
```suggestion
```

2024-09-03 12:16 UTC, vava-odoo commented on bar_industry/data/uom_category.xml
can be removed

2024-09-03 12:16 UTC, vava-odoo commented on bar_industry/data/uom_uom.xml
can be removed

2024-09-04 07:20 UTC, dhrs-odoo commented
Hello @vava-odoo 
I have incorporated the suggested changes
Please have a look at it once you are free
Thank You :innocent:

2024-09-04 07:37 UTC, vava-odoo commented
Hello @dhrs-odoo 
Could you please check the runbot errors? Multiple files to remove in this industry module + two other modules impacted by your new test.
Also, could you add the missing pos category?
Cheers

2024-09-04 09:53 UTC, dhrs-odoo commented
Hello @vava-odoo 
I have incorporated the suggested changes
Please have a look at it once you are free
Thank You 😇

2024-09-04 10:05 UTC, vava-odoo approved these changes
Perfect, thanks! Only missing the pot and it's good to merge

2024-09-04 11:42 UTC, dhrs-odoo commented
> Perfect, thanks! Only missing the pot and it's good to merge

Added the pot file

2024-09-04 15:12 UTC, merged