[ADD] sport_club: Sport Club
odoo/industry pull request #24
Opened 2023-11-02 13:45 UTC by prra-odoo

This setup is for sports clubs that rent courts to their players, handle some basic gears and have a cafeteria.
As a small company, The Club still has quite a lot of activities to manage and does all this with Odoo. 
Below are the detailed flows they use on a daily basis.

Task-3449717

2023-11-02 14:04 UTC, jva-odoo commented on sport_club/data/ir_attachment_pre.xml
> +        <field name="url">/unsplash/M2x3A8Q4JbY/.jpg</field>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo requested changes

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/data/ir_ui_menu.xml
> +    </record>
not need menu of other module

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/data/knowledge_article.xml
> +<odoo noupdate="1">
```suggestion
<odoo>
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/data/product_template.xml
> +        <field name="uom_po_id" ref="uom.product_uom_unit"/>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/data/product_template.xml
> +        <field name="uom_id" ref="uom.product_uom_unit"/>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/data/product_template.xml
> +        <field name="weight">0.01</field>
remove other module records

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/appointment_resource.xml
> +<odoo>
```suggestion
<odoo noupdate="1">
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/appointment_type.xml
> +<odoo>
```suggestion
<odoo  noupdate="1">
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/appointment_type.xml
> +        <field name="message_intro">&lt;p&gt;Meet new players!&lt;br&gt;Every Friday evening, come alone or with friends and get to play with new players.&lt;/p&gt;</field>
CDATA

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/crm_lead.xml
> +        <field name="iap_enrich_done" eval="True"/>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/res_partner.xml
> +        <field name="calendar_last_notif_ack">2023-09-20 13:12:34</field>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/res_partner.xml
> +        <field name="category_id" eval="[(6, 0, [])]"/>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/res_partner.xml
> +        <field name="mobile">lna</field>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/sale_order_line.xml
> +        <!-- <field name="state">sale</field> -->
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/website.xml
> +        <field name="crm_default_team_id" ref="sales_team.team_sales_department"/>
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/website_ir_attachments.xml
> +    </record>
remove all record with theme url

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/website_theme_apply.xml
> +#2e2714 5
```suggestion
```

2023-11-02 14:35 UTC, jva-odoo commented on sport_club/demo/website_view.xml
> +<odoo noupdate="1">
```suggestion
<odoo>
```

2023-11-03 10:14 UTC, jva-odoo requested changes

2023-11-03 10:14 UTC, jva-odoo commented on sport_club/data/ir_attachment_pre.xml
> +<odoo>
```suggestion
<odoo noupdate="1">
```

2023-11-06 11:40 UTC, jva-odoo commented on sport_club/demo/sale_order_line.xml
> +    <record id="sale_order_line_1" model="sale.order.line" context="{'studio': True, 'skip_task_generation': True, 'skip_purchase_generation': True}">
```suggestion
    <record id="sale_order_line_1" model="sale.order.line">
```

2023-11-06 11:57 UTC, jva-odoo requested changes

2023-11-06 11:57 UTC, jva-odoo commented on sport_club/data/product_template.xml
> +    <record id="product_template_10" model="product.template" context="{'studio': True, 'create_product_product': False}">
```suggestion
    <record id="product_template_10" model="product.template" context="{'create_product_product': False}">
```

2023-11-06 11:57 UTC, jva-odoo commented on sport_club/data/knowledge_article.xml
> +    <record id="knowledge_article_1" model="knowledge.article" context="{'skip_check_member_access': True}">
```suggestion
    <record id="knowledge_article_1" model="knowledge.article">
```

2023-11-06 12:03 UTC, jva-odoo approved these changes

2023-11-06 14:29 UTC, jco-odoo commented
sports_club?

2023-11-06 14:47 UTC, xavieralt commented
> sports_club?

I'll rename it :ok_hand:

2023-11-06 17:25 UTC, merged