[IMP] Microbrewery: Adding beverage features
odoo/industry pull request #280
Opened 2024-11-05 07:20 UTC by jaeschwa

This aims to improve the micro brewery module. Including the changes present in the beverage distributor. This is related to the deposit, composition of the bin that can be decomposed. The automatic creation of bills of materials and the reordering rules.

task-4266461

2024-11-26 05:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/industry/pull/280.png)](https://mergebot.odoo.com/odoo/industry/pull/280)

2024-11-26 05:16 UTC, robodoo commented
@jaeschwa I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

2024-11-27 16:07 UTC, vava-odoo requested changes
Thanks. Only reviewed the second commit for now. Could you fix it?
I'm not sure yet if I'll do a second round of review afterwards, or update it myself.

2024-11-27 16:07 UTC, vava-odoo commented on micro_brewery/data/product_product.xml
> +        <field name="website_sequence">10165</field>
Shouldn't it be published? (in demo)

2024-11-29 05:08 UTC, dhrs-odoo commented on micro_brewery/data/knowledge_article.xml
> +        <p><br /></p>
Sorry but I am not clear, that what is the use of adding rental app and rental product if there is no mention in the knowledge article ?

2024-11-29 06:02 UTC, dhrs-odoo commented on micro_brewery/data/knowledge_article.xml
> +        <h1 style="font-size: 54px;" data-oe-version="1.0">Odoo for Microbrewery</h1>
It was because I have formatted the knowledge article but now I have reverted the change

2024-11-29 06:03 UTC, dhrs-odoo commented
Hello @vava-odoo 
I have updated the changes 
Thank You :innocent:

2024-11-29 06:36 UTC, dhrs-odoo commented on micro_brewery/data/product_product.xml
> +        <field name="website_sequence">10165</field>
No it is okay

2024-11-29 13:54 UTC, vava-odoo commented
@robodoo squash

2024-11-29 13:54 UTC, robodoo commented
Merge method set to squash.

2024-11-29 14:04 UTC, vava-odoo approved these changes

2024-11-29 15:53 UTC, vava-odoo commented
@robodoo r+

2024-11-29 15:54 UTC, closed without merging