[IMP] condominium: Improving the flows
odoo/industry pull request #287
Opened 2024-11-08 10:10 UTC by dhrs-odoo

task-4226949

2024-11-18 05:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/industry/pull/287.png)](https://mergebot.odoo.com/odoo/industry/pull/287)

2024-11-18 05:27 UTC, robodoo commented
@dhrs-odoo I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

2024-11-20 11:03 UTC, vava-odoo requested changes
@dhrs-odoo Could you please review yourself with our guidelines first? I listed a few comments but there are many more... Please also avoid useless diff. And runbot is red.

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_actions_act_window.xml
> +        <field name="domain">[('plan_id', '=', 2)]</field>
what is 2?

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_actions_act_window.xml
> +                ]]></field>
useless

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_actions_act_window.xml
> +    <record id="ratios_d3a1aa4d-3ce6-449a-b6fb-c78c0a2de6e5" model="ir.actions.act_window">
improve id

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_actions_server.xml
> +    <record id="ir_act_server_split_per_property" model="ir.actions.server" forcecreate="1">
no forcecreate

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_actions_server.xml
> +properties = env['account.analytic.account'].search([('plan_id', '=', 2), ('id', 'not in', record.x_ratios.x_property.ids)])
2?

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_default.xml
> +        <field name="json_value">2</field>
2?

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_model.xml
> +    <record id="ratios_15452286-88ba-4df3-9fa0-41021f013894" model="ir.model">
id

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_model_access.xml
> +    <record id="ratios_group_system_efe40017-03f3-46ec-9551-6ac873674c42" model="ir.model.access">
id

2024-11-20 11:03 UTC, vava-odoo commented on condominium/data/ir_model_fields.xml
> +    <record id="description_ratios_1292c640-908f-4c8c-a939-20b9b55e6169" model="ir.model.fields">
id

2024-11-20 11:03 UTC, vava-odoo commented on condominium/i18n/ar.po
no need to edit .po

2024-11-21 07:29 UTC, dhrs-odoo commented
Hello @vava-odoo 
I have implemented the changes
Please have a look at it once you are free
Thank You :innocent:

2024-11-21 14:00 UTC, vava-odoo commented on condominium/data/account_analytic_plan.xml
> +    </record>
Why is this one created? I don't see why it is created.

2024-11-21 14:08 UTC, vava-odoo commented on condominium/data/ir_actions_act_window.xml
> +      </record>
```suggestion
    </record>
```

2024-11-21 14:08 UTC, vava-odoo commented on condominium/data/ir_actions_act_window.xml
> +                ]]></field>
```suggestion
```

2024-11-21 14:10 UTC, vava-odoo commented on condominium/data/ir_actions_server.xml
> +        <field name="name">Split per Owner</field>
useless diff

2024-11-21 14:13 UTC, vava-odoo commented on condominium/data/ir_model_access.xml
> +        <field name="model_id" ref="analytic.model_account_analytic_account"/>
for such a change in stable, it is safer to slightly edit the id and the name

2024-11-21 14:14 UTC, vava-odoo commented on condominium/i18n/ar.po
but the pot needs to

2024-11-21 15:45 UTC, vava-odoo requested changes
Could you please help by reducing the diff, especially the one on fields and views? :pray:

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +    <record id="default_form_view_fo_8c2be510-bad6-4e59-9ebc-227f6fd5dfcf" model="ir.ui.view">
:eyes:

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +                                <field name="x_company_id" optional="hide" />
don't we need the group multicompany?

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +                    <field name="x_active" invisible="1" />
Not needed anymore
```suggestion
```

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +                    <group name="studio_group_ae54a3">
You can remove weird names like this one
```suggestion
                    <group>
```

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +                        <group name="studio_group_ae54a3_right" />
useless, no?

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +        <field name="inherit_id" ref="default_form_view_fo_8c2be510-bad6-4e59-9ebc-227f6fd5dfcf" />
Merge these two views together

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +        <field name="inherit_id" ref="sale_subscription.sale_subscription_order_view_form" />
move it back at the top where it was please

2024-11-21 15:45 UTC, vava-odoo commented on condominium/data/ir_ui_view.xml
> +                    <field name="x_type" options="{'create_name_field': 'x_name'}" required="plan_id == 2" />
:eyes:

2024-12-02 12:25 UTC, vava-odoo approved these changes

2024-12-02 14:13 UTC, vava-odoo commented
@robodoo r+

2024-12-02 14:20 UTC, closed without merging