[ADD] Construction: added construction industry
odoo/industry pull request #94
Opened 2024-02-26 10:50 UTC by arpa-odoo

added construction industry

task-3686809

2024-04-02 13:44 UTC, vava-odoo requested changes
Hello @arpa-odoo 
Thanks for this, it works as expected :+1: 
Could you have a look at the following comments? There is a lot of them, but mostly minor ones.
Cheers!

2024-04-02 13:44 UTC, vava-odoo commented on construction/static/src/binary/hr_employee/1-image_1920
In hr_employee.xml only images starting with 4, 5 and 7 are used. You can maybe remove others?

2024-04-02 13:44 UTC, vava-odoo commented on construction/static/src/binary/res_partner/18-image_1920
Not used?

2024-04-02 13:44 UTC, vava-odoo commented on construction/static/src/binary/res_partner/14-image_1920
Not used?

2024-04-02 13:48 UTC, vava-odoo commented on construction/__manifest__.py
> +        'stock_barcode',
No barcorde
```suggestion
```

2024-04-02 13:48 UTC, vava-odoo commented on construction/__manifest__.py
> +        'hr_holidays',
no time off
```suggestion
```

2024-04-04 06:01 UTC, arpa-odoo commented on construction/data/documents_folder.xml
> +    </record>
okay

2024-04-04 12:28 UTC, arpa-odoo commented on construction/data/project_task_type.xml
> +</odoo>
yes you are correct but in the fsm_demo file this all records was unlinked..so we cant use it.

2024-04-05 05:12 UTC, arpa-odoo commented on construction/demo/fleet_cars_data.xml
> +    <record id="fleet.model_classa" model="fleet.vehicle.model">
okay

2024-04-05 05:50 UTC, arpa-odoo commented on construction/demo/project_update.xml
> +    <record id="project_update_1" model="project.update" context="{'default_project_id': ref('project_project_4')}">
no by using only project_id i got a error
null value in column "project_id" of relation "project_update" violates not-null constraint

2024-04-05 07:09 UTC, vava-odoo commented on construction/data/project_task_type.xml
> +</odoo>
But fsm_demo is only in demo, so it won't affect the industry (standard modules are without demo)

2024-04-05 07:10 UTC, vava-odoo commented on construction/demo/project_update.xml
> +    <record id="project_update_1" model="project.update" context="{'default_project_id': ref('project_project_4')}">
ok

2024-04-08 13:34 UTC, vava-odoo requested changes
Thanks for the update. It looks good and we should be merging really soon.
Please avoid losing data between reviews. Really difficult to track...
Cheers!

2024-04-08 13:34 UTC, vava-odoo commented on construction/demo/project_task.xml
> +    </record>
A task down payment?! It looks like a bug (in standard) 
```suggestion
```

2024-04-08 13:34 UTC, vava-odoo commented on construction/demo/res_partner.xml
> +        <field name="email">cth@example.com</field>
Maybe best to change that, he wants to remain incognito :smile: 
```suggestion
        <field name="email">ceth@example.com</field>
```

2024-04-08 13:34 UTC, vava-odoo commented on construction/demo/account_analytic_account.xml
> +<odoo noupdate="1">
Please bring back "Internal" one + related project.task and account.analytic.line

2024-04-08 13:34 UTC, vava-odoo commented on construction/static/src/binary/product_template/3-image_1920
Don't see where it is used

2024-04-08 13:34 UTC, vava-odoo commented on construction/static/src/binary/product_template/4-image_1920
Don't see where it is used

2024-04-08 13:55 UTC, vava-odoo commented on construction/demo/documents_document.xml
> +    </record>
Could you also remove weird standard data?
```xml
    <record id="documents.documents_image_multi_pdf_document" model="documents.document">
        <field name="active" eval="False"/>
    </record>
    <record id="documents.documents_mail_png" model="documents.document">
        <field name="active" eval="False"/>
    </record>
```

2024-04-09 11:21 UTC, vava-odoo approved these changes

2024-04-10 07:13 UTC, merged